algoritmo "Area do triangulo"
// Função : Calcular a área de um triângulo
// Autor :Gabriel Dantas
// Data : 15/03/2022
var
base: real
altura: real
total: real
inicio
// Seção de Comandos
escreval("Digite a base do triângulo: ")
leia(base)
escreval("Digite a altura do triângulo: ")
leia(altura)

escreval("----------------------")

total <-(base * altura/2)

escreval("A área desse triângulo é: ",total)

fimalgoritmo
