algoritmo "TesteHabilitação"
// Função :
// Autor : Gabriel Dantas
// Data : 21/06/2022
// Seção de Declarações 
var
idade: inteiro
habilitado: logico
teste: logico
inicio
//Seção de Comandos
escreval("Digite a sua idade: ")
leia(idade)

escreval("Você é habilitado? (responda com 'verdadeiro' ou 'falso') :")
leia(habilitado)
teste <- (idade >= 18) e (habilitado=verdadeiro)

escreval("Seu teste de Habilitação deu: ",teste)


fimalgoritmo
