algoritmo "CalculaMedia"
// Função : Calcular a Média de duas notas
// Autor : Gabriel Dantas
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2,media:real
inicio
// Dados de Entrada
escreval("Entre com um valor para P1: ")
leia(p1)
escreval("Entre com um valor para P2: ")
leia(p2)
//Fim dos Dados de Entrada

//Processamento
media <- (p1+p2)/2
//Fim do Processamento

//Dados de Saída
escreval("A média do aluno é: ", media)
//Fim dos Dados de Saída
fimalgoritmo
